// Author: Davi_MCST

ServerEvents.recipes(event => {
    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "botania:life_essence",
            "eidolon:crimson_gem",
            "botania:life_essence",
            "eidolon:crimson_gem",
            "eidolon:crimson_gem",
            "botania:life_essence",
            "eidolon:crimson_gem",
            "botania:life_essence"
        ],
	    "botania:terrasteel_ingot",
	    "botania:gaia_ingot",
	    300,
    );

    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "botania:livingrock",
            "botania:livingrock",
            "botania:livingrock",
            "botania:livingrock",
            "botania:livingrock",
            "botania:livingrock",
            "botania:livingrock",
            "botania:livingrock"
        ],
	    "forbidden_arcanus:ferrognetic_mixture",
	    "botania:mana_tablet",
	    300,
    );

    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "#forge:plates/gold",
            "#forge:plates/gold",
            "#forge:plates/gold",
            "#forge:plates/gold",
            "#forge:gems/mana_diamond",
            "#forge:gems/mana_diamond",
            "#forge:ingots/manasteel",
            "#forge:ingots/manasteel"
        ],
	    "minecraft:echo_shard",
	    "botania:mana_pylon",
	    500,
    );

    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "botania:glimmering_livingwood",
            "botania:glimmering_livingwood",
            "botania:glimmering_livingwood",
            "botania:glimmering_livingwood",
            "powah:crystal_spirited",
            "powah:crystal_spirited",
            "#forge:ingots/terrasteel",
            "#forge:ingots/terrasteel"
        ],
	    "botania:mana_pylon",
	    "botania:natura_pylon",
	    1000,
    );

    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "botania:livingrock",
            "botania:livingrock",
            "botania:livingrock",
            "botania:livingrock",
            "occultism:otherworld_sapling",
            "powah:crystal_nitro",
            "naturesaura:aura_cache"
        ],
	    "minecraft:conduit",
	    "botania:runic_altar",
	    200,
    );

    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "botania:elementium_ingot",
            "botania:elementium_ingot",
            "botania:elementium_ingot",
            "botania:elementium_ingot",
            "powah:crystal_nitro",
            "powah:crystal_nitro",
            "botania:pixie_dust",
            "botania:pixie_dust"
        ],
	    "botania:natura_pylon",
	    "botania:gaia_pylon",
	    2000,
    );

    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "minecraft:crying_obsidian",
            "minecraft:crying_obsidian",
            "minecraft:crying_obsidian",
            "minecraft:crying_obsidian",
            "mythicbotany:alfsteel_ingot",
            "mythicbotany:alfsteel_ingot",
            "mekanism_extras:alloy_thermonuclear",
            "mekanism_extras:alloy_thermonuclear"
        ],
	    "botania:gaia_pylon",
	    "mythicbotany:alfsteel_pylon",
	    4000,
    );

    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "eidolon:pewter_inlay",
            "eidolon:pewter_inlay",
            "eidolon:pewter_inlay",
            "eidolon:pewter_inlay",
            "occultism:stable_wormhole",
            "bloodmagic:blankslate",
            "bloodmagic:blankslate",
            "occultism:otherstone_pedestal"
        ],
	    "farmersdelight:cooking_pot",
	    "bloodmagic:soulforge",
	    5000,
    );

    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "bloodmagic:blankslate",
            "bloodmagic:blankslate",
            "bloodmagic:blankslate",
            "bloodmagic:blankslate",
            "eidolon:ender_calx",
            "eidolon:ender_calx"
        ],
	    "botania:livingwood",
	    "bloodmagic:blankrune",
	    50,
    );

    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "megacells:sky_steel_ingot",
            "bigreactors:graphite_block",
            "megacells:sky_steel_ingot",
            "bigreactors:graphite_block",
            "bigreactors:graphite_block",
            "megacells:sky_steel_ingot",
            "bigreactors:graphite_block",
            "megacells:sky_steel_ingot"
        ],
	    "bigreactors:basic_reactorcasing",
	    "4x bigreactors:reinforced_reactorcasing",
	    500,
    );

    event.recipes.ars_nouveau.enchanting_apparatus(
        [
            "megacells:sky_steel_ingot",
            "bigreactors:cyanite_ingot",
            "megacells:sky_steel_ingot",
            "bigreactors:cyanite_ingot",
            "bigreactors:cyanite_ingot",
            "megacells:sky_steel_ingot",
            "bigreactors:cyanite_ingot",
            "megacells:sky_steel_ingot"
        ],
	    "bigreactors:basic_turbinecasing",
	    "bigreactors:reinforced_turbinecasing",
	    500,
    );
})