// Author: Davi_MCST

StartupEvents.registry('item', event => {
	event.create('world_ash_branch').displayName('World Ash Branch').texture(`kubejs:item/world_ash_branch`)
    event.create('yggdralium_ingot').displayName('Yggdralium Ingot').texture(`kubejs:item/yggdralium_ingot`)
    event.create('yggdralium_shard').displayName('Yggdralium Shard').texture(`kubejs:item/yggdralium_shard`)
    event.create('blank_botanic_rune').displayName('Blank Botanic Rune').texture('kubejs:item/blank_botanic_rune')
    event.create('stone_dust').displayName('Stone Dust').texture('kubejs:item/stone_dust')
    event.create('foam_powder').displayName('Foam Powder').texture('kubejs:item/foam_powder')
    event.create('grand_large_plate').displayName('Grand Large Plate').texture('kubejs:item/grand_large_plate')
    event.create('large_plate_tconstruct_bloodbone').displayName('Bloodbone Large Plate').texture('kubejs:item/large_plate_tconstruct_bloodbone')
    event.create('large_plate_tconstruct_bone').displayName('Bone Large Plate').texture('kubejs:item/large_plate_tconstruct_bone')
    event.create('large_plate_tconstruct_bronze').displayName('Bronze Large Plate').texture('kubejs:item/large_plate_tconstruct_bronze')
    event.create('large_plate_tconstruct_constantan').displayName('Constantan Large Plate').texture('kubejs:item/large_plate_tconstruct_constantan')
    event.create('large_plate_tconstruct_cyanite').displayName('Cyanite Large Plate').texture('kubejs:item/large_plate_tconstruct_cyanite')
    event.create('large_plate_tconstruct_elementium').displayName('Elementium Large Plate').texture('kubejs:item/large_plate_tconstruct_elementium')
    event.create('large_plate_tconstruct_blazing_crystal').displayName('Blazing Crystal Large Plate').texture('kubejs:item/large_plate_tconstruct_blazing_crystal')
    event.create('large_plate_tconstruct_grains').displayName('Grains Of Infinity Large Plate').texture('kubejs:item/large_plate_tconstruct_grains')
    event.create('large_plate_tconstruct_iesnium').displayName('Iesnium Large Plate').texture('kubejs:item/large_plate_tconstruct_iesnium')
    event.create('large_plate_tconstruct_infused_wood').displayName('Infused Wood Large Plate').texture('kubejs:item/large_plate_tconstruct_infused_wood')
    event.create('large_plate_tconstruct_iron').displayName('Iron Large Plate').texture('kubejs:item/large_plate_tconstruct_iron')
    event.create('large_plate_tconstruct_lead').displayName('Lead Large Plate').texture('kubejs:item/large_plate_tconstruct_lead')
    event.create('large_plate_tconstruct_netherite').displayName('Netherite Large Plate').texture('kubejs:item/large_plate_tconstruct_netherite')
    event.create('large_plate_tconstruct_pig_iron').displayName('Pig Iron Large Plate').texture('kubejs:item/large_plate_tconstruct_pig_iron')
    event.create('large_plate_tconstruct_queens_slime').displayName('Queens Slime Large Plate').texture('kubejs:item/large_plate_tconstruct_queens_slime')
    event.create('large_plate_tconstruct_refined_glowstone').displayName('Refined Glowstone Large Plate').texture('kubejs:item/large_plate_tconstruct_refined_glowstone')
    event.create('large_plate_tconstruct_refined_obsidian').displayName('Refined Obsidian Large Plate').texture('kubejs:item/large_plate_tconstruct_refined_obsidian')
    event.create('large_plate_tconstruct_rose_gold').displayName('Rose Gold Large Plate').texture('kubejs:item/large_plate_tconstruct_rose_gold')
    event.create('large_plate_tconstruct_slimewood').displayName('Slimewood Large Plate').texture('kubejs:item/large_plate_tconstruct_slimewood')
    event.create('large_plate_tconstruct_soulium').displayName('Soulium Large Plate').texture('kubejs:item/large_plate_tconstruct_soulium')
    event.create('large_plate_tconstruct_starmetal').displayName('Starmetal Large Plate').texture('kubejs:item/large_plate_tconstruct_starmetal')
    event.create('large_plate_tconstruct_stone').displayName('Stone Large Plate').texture('kubejs:item/large_plate_tconstruct_stone')
    event.create('large_plate_tconstruct_uranium').displayName('Uranium Large Plate').texture('kubejs:item/large_plate_tconstruct_uranium')
    event.create('rose_gold_ingot').displayName('Rose Gold Ingot').texture('kubejs:item/rose_gold_ingot')
    event.create('queens_slime_ingot').displayName('Queens Slime Ingot').texture('kubejs:item/queens_slime_ingot')
    event.create('pigiron_ingot').displayName('Pig Iron Ingot').texture('kubejs:item/pigiron_ingot')
    event.create('blood_slime_ball').displayName('Coagulated Blood').texture('kubejs:item/blood_slime_ball')
    event.create('bloodbone').displayName('Bloodbone').texture('kubejs:item/bloodbone')
    event.create('starmetal_ingot').displayName('Starmetal Ingot').texture('kubejs:item/starmetal_ingot')
    event.create('netherite_upgrade').displayName('Netherite Upgrade').texture('kubejs:item/netherite_upgrade')
    event.create('diamond_upgrade').displayName('Diamond Upgrade').texture('kubejs:item/diamond_upgrade')
    event.create('gold_upgrade').displayName('Gold Upgrade').texture('kubejs:item/gold_upgrade')
    event.create('copper_upgrade').displayName('Copper Upgrade').texture('kubejs:item/copper_upgrade')
    event.create('creative_vending_upgrade').displayName('Creative Vending Upgrade').texture('kubejs:item/creative_vending_upgrade')
    event.create('water_upgraded_netherite_ingot').displayName('Prismarite Ingot').texture('kubejs:item/water_upgraded_netherite_ingot')
    event.create('mana_diamond_plate').displayName('Mana Diamond Plate').texture('kubejs:item/mana_diamond_plate')
    event.create('endless').displayName('Endless').texture('kubejs:item/endless')
    event.create('shard_of_creativity').displayName('Shard of Creativity').texture('kubejs:item/shard_of_creativity')
    event.create('shard_of_imunity').displayName('Shard of Imunity').texture('kubejs:item/shard_of_imunity')
    event.create('shard_of_knowledge').displayName('Shard of Knowledge').texture('kubejs:item/shard_of_knowledge')
    event.create('shard_of_mankind').displayName('Shard of Mankind').texture('kubejs:item/shard_of_mankind')
    event.create('shard_of_nature').displayName('Shard of Nature').texture('kubejs:item/shard_of_nature')
    event.create('shard_of_perserevity').displayName('Shard of Perserevity').texture('kubejs:item/shard_of_perserevity')
    event.create('shard_of_the_greater_good').displayName('Shard of the Greater Good').texture('kubejs:item/shard_of_the_greater_good')
    event.create('shard_of_the_greater_mana').displayName('Shard of the Greater Mana').texture('kubejs:item/shard_of_the_greater_mana')
    event.create('thermospiritium').displayName('Thermospiritium Ingot').texture('kubejs:item/thermospiritium')
    event.create('skin_of_gaia').displayName('Skin of Gaia').texture('kubejs:item/skin_of_gaia')
    event.create('inferium_seed_base').displayName('Inferium Seed Base').texture('kubejs:item/inferium_seed_base')
    event.create('prudentium_seed_base').displayName('Prudentium Seed Base').texture('kubejs:item/prudentium_seed_base')
    event.create('tertium_seed_base').displayName('Tertium Seed Base').texture('kubejs:item/tertium_seed_base')
    event.create('imperium_seed_base').displayName('Imperium Seed Base').texture('kubejs:item/imperium_seed_base')
    event.create('supremium_seed_base').displayName('Supremium Seed Base').texture('kubejs:item/supremium_seed_base')
    event.create('insanium_seed_base').displayName('Insanium Seed Base').texture('kubejs:item/insanium_seed_base')
    event.create('mixed_tier_2_essence').displayName('Mixed Tier 2 Essence').texture('kubejs:item/mixed_tier_2_essence')
    event.create('mixed_tier_3_essence').displayName('Mixed Tier 3 Essence').texture('kubejs:item/mixed_tier_3_essence')
    event.create('mixed_tier_4_essence').displayName('Mixed Tier 4 Essence').texture('kubejs:item/mixed_tier_4_essence')
})

StartupEvents.registry('block', event => {
    event.create('compressed_hay_bale').material('grass').hardness(1.0).displayName('Compressed Hay Bale')
	event.create('double_compressed_hay_bale').material('grass').hardness(1.0).displayName('Double Compressed Hay Bale')
})