// Author: Davi_MCST

ServerEvents.recipes(event => {
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_rose_gold', '8x kubejs:rose_gold_ingot')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_bloodbone', '8x kubejs:bloodbone')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_bone', '8x minecraft:bone')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_bronze', '8x #forge:ingots/bronze')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_constantan', '8x #forge:ingots/constantan')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_cyanite', '8x #forge:ingots/cyanite')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_elementium', '8x #forge:ingots/elementium')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_blazing_crystal', '8x powah:crystal_blazing')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_grains', '8x enderio:grains_of_infinity')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_iesnium', '8x #forge:ingots/iesnium')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_infused_wood', '8x botania:livingwood')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_iron', '8x #forge:ingots/iron')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_lead', '8x #forge:ingots/lead')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_netherite', '8x #forge:ingots/netherite')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_pig_iron', '8x kubejs:pigiron_ingot')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_queens_slime', '8x kubejs:queens_slime_ingot')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_refined_glowstone', '8x mekanism:ingot_refined_glowstone')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_refined_obsidian', '8x mekanism:ingot_refined_obsidian')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_soulium', '8x #forge:ingots/soulium')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_slimewood', '8x minecraft:slime_ball')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_starmetal', '8x kubejs:starmetal_ingot')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_stone', '8x #forge:stone')
    event.recipes.thermal.press('kubejs:large_plate_tconstruct_uranium', '8x #forge:ingots/uranium')
})