// Author: Davi_MCST

ServerEvents.recipes(event => {
    const {awakening,enchanter,infusion,reprocessor,soul_extraction,soulium_spawner} = event.recipes.mysticalagriculture;
    
// Tier 1 Seeds

    infusion(
        "mysticalagriculture:stone_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:inferium_block",4),
            Item.of("allthecompressed:stone_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:dirt_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:inferium_block",4),
            Item.of("allthecompressed:dirt_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:ice_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:inferium_block",4),
            Item.of("minecraft:blue_ice",4)
        ]
    );

    infusion(
        "mysticalagriculture:wood_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:inferium_block",4),
            Item.of("allthecompressed:oak_log_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:deepslate_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:inferium_block",4),
            Item.of("allthecompressed:deepslate_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:air_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:inferium_block",4),
            Item.of("mysticalagriculture:air_agglomeratio",4)
        ]
    );

    infusion(
        "mysticalagriculture:earth_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:inferium_block",4),
            Item.of("mysticalagriculture:earth_agglomeratio",4)
        ]
    );

    infusion(
        "mysticalagriculture:fire_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:inferium_block",4),
            Item.of("mysticalagriculture:fire_agglomeratio",4)
        ]
    );

    infusion(
        "mysticalagriculture:water_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:inferium_block",4),
            Item.of("mysticalagriculture:water_agglomeratio",4)
        ]
    );

// Tier 2 Seeds

    infusion(
        "mysticalagriculture:nature_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("mysticalagriculture:nature_agglomeratio",4)
        ]
    );

    infusion(
        "mysticalagriculture:dye_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("mysticalagriculture:dye_agglomeratio",4)
        ]
    );

    infusion(
        "mysticalagriculture:nether_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("mysticalagriculture:nether_agglomeratio",4)
        ]
    );

    infusion(
        "mysticalagriculture:coal_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("allthecompressed:coal_block_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:coral_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("mysticalagriculture:coral_agglomeratio",4)
        ]
    );

    infusion(
        "mysticalagriculture:honey_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("mysticalagriculture:honey_agglomeratio",4)
        ]
    );

    infusion(
        "mysticalagriculture:amethyst_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("allthecompressed:amethyst_block_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:silicon_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("#forge:silicon",4)
        ]
    );

    infusion(
        "mysticalagriculture:sulfur_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("#forge:dusts/sulfur",4)
        ]
    );

    infusion(
        "mysticalagriculture:aluminum_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("#forge:ingots/aluminum",4)
        ]
    );

    infusion(
        "mysticalagriculture:saltpeter_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("#forge:dusts/saltpeter",4)
        ]
    );

    infusion(
        "mysticalagriculture:apatite_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("#forge:storage_blocks/apatite",4)
        ]
    );

    infusion(
        "mysticalagriculture:grains_of_infinity_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("#forge:dusts/grains_of_infinity",4)
        ]
    );

    infusion(
        "mysticalagriculture:mystical_flower_seeds",
        "mysticalagriculture:prosperity_seed_base",
        [
            Item.of("mysticalagriculture:prudentium_block",4),
            Item.of("mysticalagriculture:mystical_flower_agglomeratio",4)
        ]
    );

// Tier 3 Seeds

    infusion(
        "mysticalagriculture:iron_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("allthecompressed:iron_block_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:certus_quartz_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("ae2:quartz_block",4)
        ]
    );

    infusion(
        "mysticalagriculture:copper_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("allthecompressed:copper_block_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:nether_quartz_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("allthecompressed:quartz_block_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:glowstone_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("allthecompressed:glowstone_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:redstone_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("allthecompressed:redstone_block_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:obsidian_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("allthecompressed:obsidian_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:prismarine_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("#forge:gems/prismarine",4)
        ]
    );

    infusion(
        "mysticalagriculture:tin_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("#forge:storage_blocks/tin",4)
        ]
    );

    infusion(
        "mysticalagriculture:bronze_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("#forge:storage_blocks/bronze",4)
        ]
    );

    infusion(
        "mysticalagriculture:silver_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("#forge:storage_blocks/silver",4)
        ]
    );

    infusion(
        "mysticalagriculture:lead_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("#forge:storage_blocks/lead",4)
        ]
    );

    infusion(
        "mysticalagriculture:graphite_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("#forge:storage_blocks/graphite",4)
        ]
    );

    infusion(
        "mysticalagriculture:copper_alloy_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("allthecompressed:copper_alloy_block_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:redstone_alloy_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("allthecompressed:redstone_alloy_block_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:conductive_alloy_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("allthecompressed:conductive_alloy_block_4x",4)
        ]
    );

    infusion(
        "mysticalagriculture:manasteel_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("#forge:storage_blocks/manasteel",4)
        ]
    );

    infusion(
        "mysticalagriculture:sky_stone_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:tertium_block",4),
            Item.of("ae2:sky_stone_block",4)
        ]
    );

// Tier 4 Seeds
    awakening(
        "mysticalagriculture:gold_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "allthecompressed:gold_block_5x",
            "allthecompressed:gold_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:lapis_lazuli_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "allthecompressed:lapis_block_5x",
            "allthecompressed:lapis_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:end_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:end_agglomeratio",
            "mysticalagriculture:end_agglomeratio",
        ]
    );

    awakening(
        "mysticalagriculture:steel_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "allthecompressed:dark_steel_block_5x",
            "allthecompressed:dark_steel_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:nickel_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/nickel",
            "#forge:storage_blocks/nickel",
        ]
    );

    awakening(
        "mysticalagriculture:electrum_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/electrum",
            "#forge:storage_blocks/electrum",
        ]
    );

    awakening(
        "mysticalagriculture:constantan_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/constantan",
            "#forge:storage_blocks/constantan",
        ]
    );

    awakening(
        "mysticalagriculture:invar_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/invar",
            "#forge:storage_blocks/invar",
        ]
    );

    awakening(
        "mysticalagriculture:uranium_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/uranium",
            "#forge:storage_blocks/uranium",
        ]
    );

    awakening(
        "mysticalagriculture:ruby_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/ruby",
            "#forge:storage_blocks/ruby",
        ]
    );

    awakening(
        "mysticalagriculture:sapphire_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/sapphire",
            "#forge:storage_blocks/sapphire",
        ]
    );

    awakening(
        "mysticalagriculture:soulium_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:soulium_block",
            "mysticalagriculture:soulium_block",
        ]
    );

    awakening(
        "mysticalagriculture:signalum_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/signalum",
            "#forge:storage_blocks/signalum",
        ]
    );

    awakening(
        "mysticalagriculture:lumium_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/lumium",
            "#forge:storage_blocks/lumium",
        ]
    );

    awakening(
        "mysticalagriculture:soularium_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "allthecompressed:soularium_block_5x",
            "allthecompressed:soularium_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:dark_steel_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "allthecompressed:dark_steel_block_5x",
            "allthecompressed:dark_steel_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:pulsating_alloy_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "allthecompressed:pulsating_alloy_block_5x",
            "allthecompressed:pulsating_alloy_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:energetic_alloy_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "allthecompressed:energetic_alloy_block_5x",
            "allthecompressed:energetic_alloy_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:elementium_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/elementium",
            "#forge:storage_blocks/elementium",
        ]
    );

    awakening(
        "mysticalagriculture:osmium_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/osmium",
            "#forge:storage_blocks/osmium",
        ]
    );

    awakening(
        "mysticalagriculture:fluorite_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/fluorite",
            "#forge:storage_blocks/fluorite",
        ]
    );

    awakening(
        "mysticalagriculture:refined_glowstone_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/refined_glowstone",
            "#forge:storage_blocks/refined_glowstone",
        ]
    );

    awakening(
        "mysticalagriculture:refined_obsidian_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/refined_obsidian",
            "#forge:storage_blocks/refined_obsidian",
        ]
    );

    awakening(
        "mysticalagriculture:compressed_iron_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "#forge:storage_blocks/compressed_iron",
            "#forge:storage_blocks/compressed_iron",
        ]
    );

    awakening(
        "mysticalagriculture:fluix_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "ae2:fluix_block",
            "ae2:fluix_block",
        ]
    );

    awakening(
        "mysticalagriculture:energized_steel_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "allthecompressed:energized_steel_block_5x",
            "allthecompressed:energized_steel_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:blazing_crystal_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",20),
            Item.of("mysticalagriculture:fire_essence",20),
            Item.of("mysticalagriculture:water_essence",20),
            Item.of("mysticalagriculture:earth_essence",20)
        ],
        [
            "mysticalagriculture:imperium_block",
            "mysticalagriculture:imperium_block",
            "allthecompressed:blazing_crystal_block_5x",
            "allthecompressed:blazing_crystal_block_5x",
        ]
    );

// Tier 5 Seeds
    awakening(
        "mysticalagriculture:diamond_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "allthecompressed:diamond_block_5x",
            "allthecompressed:diamond_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:emerald_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "allthecompressed:emerald_block_5x",
            "allthecompressed:emerald_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:netherite_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "allthecompressed:netherite_block_5x",
            "allthecompressed:netherite_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:end_steel_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "allthecompressed:end_steel_block_5x",
            "allthecompressed:end_steel_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:terrasteel_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "#forge:storage_blocks/terrasteel",
            "#forge:storage_blocks/terrasteel",
        ]
    );

    awakening(
        "mysticalagriculture:enderium_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "#forge:storage_blocks/enderium",
            "#forge:storage_blocks/enderium",
        ]
    );

    awakening(
        "mysticalagriculture:vibrant_alloy_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "allthecompressed:vibrant_alloy_block_5x",
            "allthecompressed:vibrant_alloy_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:uraninite_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "allthecompressed:uraninite_block_5x",
            "allthecompressed:uraninite_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:cyanite_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "#forge:storage_blocks/cyanite",
            "#forge:storage_blocks/cyanite",
        ]
    );

    awakening(
        "mysticalagriculture:niotic_crystal_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "allthecompressed:niotic_crystal_block_5x",
            "allthecompressed:niotic_crystal_block_5x",
        ]
    );

    awakening(
        "mysticalagriculture:spirited_crystal_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",30),
            Item.of("mysticalagriculture:fire_essence",30),
            Item.of("mysticalagriculture:water_essence",30),
            Item.of("mysticalagriculture:earth_essence",30)
        ],
        [
            "mysticalagriculture:supremium_block",
            "mysticalagriculture:supremium_block",
            "allthecompressed:spirited_crystal_block_5x",
            "allthecompressed:spirited_crystal_block_5x",
        ]
    );

// Tier 6 Seeds
    awakening(
        "mysticalagriculture:nether_star_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",40),
            Item.of("mysticalagriculture:fire_essence",40),
            Item.of("mysticalagriculture:water_essence",40),
            Item.of("mysticalagriculture:earth_essence",40)
        ],
        [
            "mysticalagradditions:insanium_block",
            "mysticalagradditions:insanium_block",
            "extendedcrafting:nether_star_block",
            "extendedcrafting:nether_star_block",
        ]
    );

    awakening(
        "mysticalagriculture:dragon_egg_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",40),
            Item.of("mysticalagriculture:fire_essence",40),
            Item.of("mysticalagriculture:water_essence",40),
            Item.of("mysticalagriculture:earth_essence",40)
        ],
        [
            "mysticalagradditions:insanium_block",
            "mysticalagradditions:insanium_block",
            "mysticalagradditions:dragon_scale",
            "mysticalagradditions:dragon_scale",
        ]
    );

    awakening(
        "mysticalagriculture:gaia_spirit_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",40),
            Item.of("mysticalagriculture:fire_essence",40),
            Item.of("mysticalagriculture:water_essence",40),
            Item.of("mysticalagriculture:earth_essence",40)
        ],
        [
            "mysticalagradditions:insanium_block",
            "mysticalagradditions:insanium_block",
            "botania:gaia_ingot",
            "botania:gaia_ingot",
        ]
    );

    awakening(
        "mysticalagriculture:neutronium_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",40),
            Item.of("mysticalagriculture:fire_essence",40),
            Item.of("mysticalagriculture:water_essence",40),
            Item.of("mysticalagriculture:earth_essence",40)
        ],
        [
            "mysticalagradditions:insanium_block",
            "mysticalagradditions:insanium_block",
            "avaritia:neutronium_block",
            "avaritia:neutronium_block",
        ]
    );

    awakening(
        "mysticalagriculture:nitro_crystal_seeds",
        "mysticalagriculture:soulium_seed_base",
        [
            Item.of("mysticalagriculture:air_essence",40),
            Item.of("mysticalagriculture:fire_essence",40),
            Item.of("mysticalagriculture:water_essence",40),
            Item.of("mysticalagriculture:earth_essence",40)
        ],
        [
            "mysticalagradditions:insanium_block",
            "mysticalagradditions:insanium_block",
            "allthecompressed:nitro_crystal_block_5x",
            "allthecompressed:nitro_crystal_block_5x",
        ]
    );
})